title: <p align="center"> Gianmarco Russo </p>

logo: "/images/profilepic.jpeg?raw=true"

description:
  <p align="center">
  Milan, Italy
  <br> sezc.gianmarco.russo@gmail.com
  <br> <a href="pdf/Gianmarco_Russo_ENG.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/grusso98/">LinkedIn</a> |
  <a href="https://github.com/grusso98">GitHub</a> 
  </p>
  <br> 25 y/o | M. Sc. in Data Science | B. Sc. in Computer Engineering </p>
  
theme: jekyll-theme-minimal


