title: <p align="center"> Gianmarco Russo </p>

logo: "/images/profilepic.jpeg?raw=true"

description:
  <p align="center">
  Milan, Italy
  <br> sezc.gianmarco.russo@gmail.com
  <br> <a href="pdf/Gianmarco_Russo_ENG.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/grusso98/">LinkedIn</a> |
  <a href="https://github.com/grusso98">GitHub</a> 
  </p>
  
  <p align="justify">
  I am junior <b>data scientist</b> who enjoys connecting the dots by the use of technology. 
  <br><br>
  I've recently obtained a <b>Master's Degree in Data Science at University of Milano-Bicocca</b>, where I have received solid training in all the major fields of Data Science, like Statistics, Computer Science, Data Engineering, Machine Learning and more.
  My IT education (<b>Bachelor's Degree in Computer Engineering</b>), has allowed me to develop strong analytical, mathematical and programming skills, which have proven useful in my current career path.
  I consider myself a kind, empathetic, creative and determined person. I am pragmatic and organized, yet flexible.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal


